### ISSUE TITLE
Pencil and plus Icons not showing for adding images

### ISSUE THREAD

**Issue by SSFlyer01** [2sic/app-swiper#20] opened 2024-07-02 20:54 UTC
2SXC v.17.10.00 - Slider v.2.17.1
After adding the SwiperSlider app, I can rotate through the menu options, but there is no plus icon to add slide images. The only way to do it is to add a slide through the slider configuration in advanced settings.
Once I add a single image, the correct icons appear for adding/editing the slides.

**Comment by iJungleboy** [comment] 2024-07-03 04:57
This is by design - I believe the initial slide even has an arrow pointing to than functionality.

Reason is that at first you have to create the "slide set" before adding slides to that set.

**Comment by SSFlyer01** [comment] 2024-07-03 05:12
Actually, the initial slide has an arrow pointing to where they _should_ be. This functionality is completely different than the older versions.

**Comment by iJungleboy** [comment] 2024-07-03 07:21
hmm... @SSFlyer01 could you post some print screens?

**Comment by SSFlyer01** [comment] 2024-07-03 17:15
Sure, this is the first screen after adding the app:
![DemoSlide](https://github.com/2sic/app-swiper/assets/106369752/86c1ab41-5a9c-44f9-991c-13eae03f5320)

After giving it a title, I get this. I can rotate through the options, but no plus or edit icons are there:
![EmptySlider](https://github.com/2sic/app-swiper/assets/106369752/1cd0d49b-c843-46c4-ba6c-4b38328d9ac5)

To add the first slide, I need to go to the slider configuration and add the first slide, here:
![AdvancedSliderConfig](https://github.com/2sic/app-swiper/assets/106369752/b9316675-8aeb-4861-b7e8-3c22aff88af1)

I'm pretty sure this is not by design, and is completely unintuitive.
Thanks for taking a look!

**Comment by iJungleboy** [comment] 2024-07-04 05:13
@ropalko could you check that the "first use" experience is still correct?

**Comment by ropalko** [comment] 2024-07-04 08:11
Hello =)
It is a 2sxc bug that will be fixed with the next release

**Comment by iJungleboy** [comment] 2024-07-04 09:16
fixed in next release, hopefully this week a new v18 will come out.

**Closed as completed by iJungleboy** 2024-07-04 09:16 UTC
